### ISSUE TITLE
Dark Souls Remastered

### ISSUE THREAD

**Issue by rajwayeuh** [strato-emu/compat-list#1669] opened 2024-09-17 09:57 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Tested Build

Skyline V72

### Android Version

13

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_poco_x3_pro-10802.php

### Game Behaviour

Bruh the 
![Screenshot_20240917-164628_Skyline Edge](https://github.com/user-attachments/assets/0847e6a7-287a-4ee3-832c-306e9f37fa48)
keyboard won't appear

### Is Log Level is set to 'Info'?

- [ ] Yes

### Log file

idk where

**Comment by Crytonics** [comment] 2024-09-21 16:58
Duplicate of #167

**Closed by Crytonics** 2024-09-21 16:58 UTC
